version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bcrypt
    versions:
    - 5.0.0
  - dependency-name: pug
    versions:
    - 3.0.0
